tronbyt/server

Dockerfile, clone_system_apps_repo.py, docker-compose.yaml, requirements.txt, run
- split image creation into two parts (builder and runtime) to avoid adding parts only needed at buildtime to the runtime image
- update the system apps clone at container startup
- use exec-form for CMD to ensure that tronbyt-server runs exec pid 1 and thus receives signals
- fix a few other hadolint warning
- copy the app code into the image to remove the need for cloning this repo (mount `/app` to overlay this during development)
=> Reduce container image size

.dockerignore, Dockerfile, run
Use Alpine base images and package the Python dependencies in a separate builder stage so that the runtime image doesn't have to contain the toolchain required to build the Python packages (gcc et.al.).
This reduces the final image size from 493 MB to 271 MB.
=> Further reduce Docker image size

.env.example, .gitignore, Caddyfile, README.md, docker-compose.yaml, tronbyt_server/__init__.py, tronbyt_server/api.py, tronbyt_server/manager.py
This requires another change in the frontend which currently assumes all URLs to be HTTP (the places which use `SERVER_HOSTNAME`).
=> Add an example how to front tronbyt-server with Caddy for automatic HTTPS

tronbyt_server/__init__.py
The setting was ineffective previously because it was never read from environment and the default (5100) was always used.
=> Actually use PIXLET_RENDER_PORT1 from environment

Caddyfile, Dockerfile, docker-compose.dev.yaml, docker-compose.https.yaml, docker-compose.yaml, requirements.txt, tronbyt_server/manager.py, tronbyt_server/templates/manager/configapp.html
This removes the need to expose the ports used by Pixlet.
Change the way the Flask app interact with Pixlet: instead of pointing the client to the pixlet instance's port, let the Flask app forward requests.
With this change, the app only exposes a single port which improves scalability (no need to adjust port configs after adding a user) allows TLS configuration with a given certificate only using gunicorn (example coming in a future PR).
The pixlet processes are still allocated static port numbers, which could be improved independently.
=> Proxy requests to `pixlet serve` through the Flask app

Dockerfile, docker-compose.dev.yaml, docker-compose.https.yaml, docker-compose.yaml, tronbyt_server/__init__.py, tronbyt_server/manager.py
This removes the need to run a pixlet container serving an API and enables pixlet's HTTP cache.
Fixes #74
Requires https://github.com/tavdog/pixlet/pull/9
=> Use libpixlet to render applets

.env.example, tronbyt_server/__init__.py
The allocated buffer was 4x the needed size due to a wrong type (`* int32` instead of `* unsigned char`).
=> Fix large image files when using libpixlet

Dockerfile, requirements.txt, tronbyt_server/manager.py
It didn't really work because there was no websocket server running. The websocket is used by Pixlet to watch for changes in the applet source files which isn't very useful within tronbyt-server. Apps could change within a container when refreshing a repository, but in that case, the configapp page should just be refreshed.
I looked into flask-sockets, but this is deprecated. The replacement flask-sock doesn't have a Debian package, so I don't think this is really worth it.
=> Remove websocket proxy for pixlet

tronbyt_server/db.py, tronbyt_server/manager.py
Instead of setting the seconds for `end_time` to `59`, we truncate the current time to minutes. This also catches the case in the last second of the day because the `microsecond` field was not set to `999999`.
=> Simplify get_is_app_schedule_active

tronbyt_server/manager.py, tronbyt_server/models/app.py
add app field to indicate if the last render was empty and to not show the last non blank webp which will be shown in the device index but shouldn't be sent to the device.
=> Empty last render

tronbyt_server/manager.py
Use the number of configured apps as a dynamic limit instead.
=> Remove maximum recursion limit to allow skipping more than 10 apps.

.github/workflows/build.yml, README.md, gunicorn.conf.py, run.development, tronbyt_server/__init__.py, tronbyt_server/runcmd
Opening the dynamic library pre-fork already runs static initialization Go code, causing post-fork calls to deadlock.
This allows using the `preload_app` option provided by unicorn which ensures that application init code is only run once in the parent process.
Fixes https://github.com/tronbyt/server/issues/176
=> Ensure that libpixlet is loaded after forking worker processes

Dockerfile
This can be overridden with the `--user` flag for the `docker` command or a `user` setting in a Compose file.
=> Run the container as a non-root user to reduce attack surface

tronbyt_server/db.py
Returning an invalid zone name from `tzname()` causes failures in apps like `gradientclock`.
Fixes https://github.com/tronbyt/server/issues/142
=> Fix the device timezone name.

tronbyt_server/db.py, tronbyt_server/templates/manager/update.html, tronbyt_server/translations/de/LC_MESSAGES/messages.po
add the option to put the string "legacy_brightness" in device notes fields to use the old scale.
=> use new scale for percentage brightness in new firmware.

tronbyt_server/api.py, tronbyt_server/manager.py
- use different file names for images pushed within the same second
- ensure pushed images are delivered in order
- only wake up a single thread to push images over a websocket because a pushed image is consumed (deleted) when it is delivered
- don't disconnect the websocket connection when `next_image` throws an exception, but log the error and continue
=> Increase robustness of pushing images

.dockerignore, .gitignore, Dockerfile, docker-compose.dev.yaml, docker-compose.https.yaml, docker-compose.redis.yaml, docker-compose.yaml, tronbyt_server/__init__.py, tronbyt_server/db.py, tronbyt_server/manager.py, tronbyt_server/system_apps.py, tronbyt_server/webp/README
In order to distribute tronbyt-server as a package, the directory layout needs to be changed. The package will contain static data like code and templates and live in a read-only location, so we can no longer write data like rendered images, the system app repo, app metadata, and app previews to the same location.
This change moves the dynamic data to a consolidated location. In a container, this is mounted as `/app/data`, but it can be configured for bare-metal installations using the `DATA_DIR` environment variable. This move causes a small one-time discontinuity, but no data loss:
- the system apps repo will be cloned one again
- the app previews will be broken until each app is rendered again
Before:
- /app/system-apps: dynamic data (discardable)
- /app/system-apps.json: dynamic data …
=> Separate dynamic from static data

README.md, tronbyt_server/__init__.py
This is a no-op for Docker Compose where the `.env` file is read by Compose itself, but it is useful for local development and bare metal deployments where the `.env` file may not be in the same directory hierarchy as the source code.
=> Look for `.env` in the current working directory.

.devcontainer/devcontainer.json, tronbyt_server/db.py
This facilitates future schema migrations. Whenever we make a breaking change, we'll have to update the current version and add a migration step.
=> Add a meta table to keep track of schema versions

tronbyt_server/templates/manager/update.html
This fixes how the page displays `0` values of `night_brightness`, `night_start`, and `night_end`. If any value was set to `0`, the page would show the default values instead (i.e. `1`, `22`, and `6`, respectively).
=> Fix display of zero values

tronbyt_server/manager.py, tronbyt_server/models/app.py, tronbyt_server/models/device.py
With this change, apps can indicate in their manifests whether they support rendering at 2x the normal canvas size (128x64 instead of 64x32). When a 2x app is rendered for a wide device, the app produces a larger image instead of scaling up the regular size.
=> Add support for 2x apps

.env.example, docker-compose.dev.yaml, tronbyt_server/__init__.py, tronbyt_server/auth.py
=> add max users env var and register check

tests/test_api_keys.py, tests/test_devices_api.py, tronbyt_server/api.py, tronbyt_server/auth.py, tronbyt_server/db.py, tronbyt_server/manager.py, tronbyt_server/models/user.py, tronbyt_server/templates/auth/edit.html, tronbyt_server/translations/de/LC_MESSAGES/messages.po
The goal is to support device discovery for home assistant integrations, by allowing a user to access the list of devices via an API key.
* Adds API key to user model, along with migration and ability to edit
* Adds GET /v0/devices endpoint that returns a list of the user's devices given their provided API key
* Update the GET/PATCH /v0/devices/id endpoint to accept user's API key in addition to the device API key.
* Add unit tests
The home assistant custom integration that uses this implementation is at https://github.com/gxlabs/tronbyt-homeassistant
=> Add user API key and devices list endpoint

.devcontainer/postCreateCommand.sh, .github/workflows/build.yml, Dockerfile, tronbyt_server/__init__.py
I'm getting a nil pointer dereference error from pixlet on the latest `main` for both the server and pixlet:
```
Jul 02 04:28:56 tronbyt tronbyt-server[70752]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 02 04:28:56 tronbyt tronbyt-server[70752]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x400 pc=0x7ed354dae5e0]
Jul 02 04:28:56 tronbyt tronbyt-server[70752]: goroutine 17 [running, locked to thread]:
Jul 02 04:28:56 tronbyt tronbyt-server[70752]: main._Cfunc_GoString(...)
Jul 02 04:28:56 tronbyt tronbyt-server[70752]:         _cgo_gotypes.go:101
Jul 02 04:28:56 tronbyt tronbyt-server[70752]: main.render_app(0xc000074e60?, 0x7ed3569072f0, 0x40, 0x20, 0x1, 0x3a98, 0x7530, 0x0, 0x1, 0x400)
Jul 02 04:28:56 tronbyt tronbyt-server[70752]: …
```
=> add filter param to pixlet call

tronbyt_server/manager.py
=> don't call g.user during a render call. might not be logged in.

tronbyt_server/templates/manager/configapp.html
I've noticed when updating config for an app, every change triggers a preview update. For plugins that are slower to render, these pile up and cause the server to go unresponsive. It's especially bad if I drag on the color picker.
This PR debounces `updateConfigAndPreview` so that the preview doesn't update until values have stopped changing for 100ms (see example video below).
Ideally, this should be done on the server-side too but I'm not familiar enough with WSGI and all of the AI solutions seemed hacky, so this is only client-side for now.
Edit: The debounce function was inspired by [You-Dont-Need-Lodash-Underscore](https://you-dont-need.github.io/You-Dont-Need-Lodash-Underscore/#/?id=_debounce).
<details>
<summary>Before</summary>
<video …
=> fix: debounce config preview updates

tests/conftest.py, tests/test_api.py, tests/test_api_keys.py, tests/test_app_create_edit_delete.py, tests/test_device_operations.py, tests/test_devices_api.py, tests/test_files_upload+delete.py, tests/test_register+login.py, tests/test_user_registration.py, tests/utils.py, tronbyt_server/auth.py, tronbyt_server/db.py, tronbyt_server/templates/auth/register_owner.html
This change implements an onboarding flow for new installations. When the server is started for the first time with no users in the database, the user is prompted to create an initial admin user.
- A new route `/auth/register_owner` is added to handle the creation of the first admin user.
- The `init_db` function is modified to no longer create a default admin user.
- The `/auth/login` and `/auth/register` routes now redirect to the owner registration page if no users exist.
- Tests have been updated to accommodate the new onboarding flow. A new `auth_client` fixture is introduced to simplify test setup for authenticated routes.
Fixes #327
=> feat: Implement owner onboarding flow

GEMINI.md, pdm.lock, pyproject.toml, tronbyt_server/manager.py, tronbyt_server/sync.py
The default syncronization method remains Multiprocessing, but installations which use Redis already for cache might want to leverage that for a more robust, production-ready solution. This remains completely optional to that Tronbyt Server can be run without any external dependencies.
=> Optionally use Redis Pub/Sub for WebSocket synchronization

.github/workflows/build.yml, tests/conftest.py, tests/test_api.py, tests/test_api_keys.py, tests/test_app_create_edit_delete.py, tests/test_device_operations.py, tests/test_devices_api.py, tests/test_files_upload+delete.py, tests/test_websockets.py, tests/utils.py, tronbyt_server/main.py, tronbyt_server/routers/api.py, tronbyt_server/routers/manager.py, tronbyt_server/routers/websockets.py, tronbyt_server/sync.py
The `app` fixture in `tests/conftest.py` was function-scoped, causing a new database to be created for each test. This was slow.
This change makes the `app` fixture session-scoped, so the application and database are created only once per test session.
To ensure test isolation, the following changes were also made:
- A single database connection is shared across the test session and injected into the app.
- A fixture (`db_cleanup`) cleans all database tables after each test.
- A fixture (`settings_cleanup`) restores application settings after each test to prevent state leakage.
fix(api): Return 404 for non-existent devices
The `/v0/devices/{device_id}` endpoint was returning a 400 Bad Request when a device was not found. This was because the `validate_device_id` check was being performed …
=> FastAPI: more and faster tests, WebSocket refactor
