tronbyt/server

.github/workflows/publish.yml
Dockerfile

Here's a link to a successful run: https://github.com/IngmarStein/tronbyt-server/actions/runs/13209367928/job/36879784374
And the resulting artifact: https://github.com/ingmarstein/tronbyt-server/pkgs/container/tronbyt-server

Fix branch name in workflow

---

.github/workflows/publish.yml
README.md

- Remove some architectures from build-push-action
- Update README

Fix multi-platform build timeout

---

.github/workflows/build.yml
.gitignore
Dockerfile
babel.cfg
requirements.txt
tronbyt_server/__init__.py
tronbyt_server/templates/auth/edit.html
tronbyt_server/templates/auth/login.html
tronbyt_server/templates/auth/register.html
tronbyt_server/templates/base.html
tronbyt_server/templates/manager/addapp.html
tronbyt_server/templates/manager/adminindex.html
tronbyt_server/templates/manager/configapp.html
tronbyt_server/templates/manager/create.html
tronbyt_server/templates/manager/firmware.html
tronbyt_server/templates/manager/firmware_form.html
tronbyt_server/templates/manager/index.html
tronbyt_server/templates/manager/update.html
tronbyt_server/templates/manager/updateapp.html
tronbyt_server/templates/manager/uploadapp.html
tronbyt_server/translations/de/LC_MESSAGES/messages.po

This also changes the base image from bookworm to trixie to align the babel versions used for testing vs inside the container (v2 and v3 have incompatible APIs).

Make app localizable and add German translation.

---

tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/templates/manager/adminindex.html
tronbyt_server/templates/manager/index.html
tronbyt_server/templates/manager/update.html
tronbyt_server/translations/de/LC_MESSAGES/messages.po

Add handler to delete non-admin users

---

Dockerfile
tronbyt_server/__init__.py
tronbyt_server/api.py
tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/templates/manager/update.html
tronbyt_server/translations/de/LC_MESSAGES/messages.po

- configurable end time (instead of fixed 6 am)
- separate flag to enabled/disable night mode
- expose night mode as `autoDim` device property for the Tidbyt API (fixes #96)

Night mode enhancements:

---

clone_system_apps_repo.py
tronbyt_server/templates/manager/addapp.html

Try "screenshot.{webp,gif,png}" if no preview was found using an app's

---

tronbyt_server/manager.py
tronbyt_server/templates/auth/edit.html
tronbyt_server/translations/de/LC_MESSAGES/messages.po

Add buttons to refresh system and user repos

---

.github/workflows/build.yml
tests/test_api.py
tests/utils.py
tronbyt_server/__init__.py
tronbyt_server/api.py
tronbyt_server/auth.py
tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/models/device.py

Also: regenerate apps JSON after refreshing the system repo

Fix many CodeQL findings

---

clone_system_apps_repo.py
tronbyt_server/manager.py

modification to clone_system_repo script to omit any apps from the generated json file if the app filename appears in the broken_apps.txt house in the tronbyt/apps repo.

open broken_apps.txt and skip any found

---

tronbyt_server/db.py
tronbyt_server/manager.py

just pull the timzone str from device object and try to convert server time to device timezone before comparing the start and end times for the app.

add tz handling for app scheduling

---

tronbyt_server/db.py

fixes the max recursion reached during minute 59

Recurse schedule time bug

---

tests/test_app_create_edit_delete.py
tests/test_device_operations.py
tests/utils.py
tronbyt_server/api.py
tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/templates/manager/create.html
tronbyt_server/templates/manager/index.html
tronbyt_server/templates/manager/update.html

change brightness to scale 0 - 5

---

tests/test_app_create_edit_delete.py

configapp test with mocks for pixlet

---

Dockerfile
requirements.txt
tronbyt_server/manager.py

Use tzlocal to get the local timezone in Olson format

---

tronbyt_server/__init__.py
tronbyt_server/manager.py

Distinguish between app failures and empty results (no screens)

---

tronbyt_server/manager.py
tronbyt_server/models/app.py

For now, this is in addition to the config files on disk. Eventually, the config files will stop being written.

Store app configs in the database

---

tronbyt_server/manager.py
tronbyt_server/templates/manager/index.html
tronbyt_server/templates/manager/updateapp.html

edit config button onn updateapp page.
set default interval for new devices.

collapse apps list on index if multiple devices. 

---

tronbyt_server/manager.py

Even for pushed (ephemeral) images.

Ensure that Tronbyt-Brightness and Tronbyt-Dwell-Secs are always set.

---

.dockerignore
tronbyt_server/api.py
tronbyt_server/db.py
tronbyt_server/manager.py

This can be used to implement notifications, see https://github.com/tronbyt/server/issues/187.

Add an endpoint to push apps (in addition to images)

---

tronbyt_server/manager.py
tronbyt_server/templates/auth/edit.html
tronbyt_server/templates/manager/configapp.html
tronbyt_server/templates/manager/create.html
tronbyt_server/templates/manager/import_config.html
tronbyt_server/templates/manager/update.html

Import export device

---

.gitignore
tests/test_device_operations.py
tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/templates/manager/firmware.html

put all generated firmware files in "generated" dir.  Delete them after 10 minutes from creation.

Delete stale firmware during health check

---

tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/models/device.py
tronbyt_server/templates/manager/index.html

reduces redundant logic for parse device timezone.

use get_device_timezone everywhere

---

.pre-commit-config.yaml
tests/test_files_upload+delete.py
tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/models/device.py
tronbyt_server/templates/manager/addapp.html
tronbyt_server/templates/manager/index.html
tronbyt_server/templates/manager/uploadapp.html

Move the upload button to the addapps page.  add a delete link at the bottom of each custom app.  Take the user back to addapp page after upload or delete.

Upload and delete buttons

---

.dockerignore
Dockerfile
README.md
docker-compose.dev.yaml
docker-compose.https.yaml
docker-compose.redis.yaml
docker-compose.yaml
run
tronbyt_server/api.py
tronbyt_server/manager.py
tronbyt_server/system_apps.py
tronbyt_server/templates/manager/create.html

This differs from https://github.com/tronbyt/server/pull/202 in the following ways:
- The image doesn't set `USER` so continues to use `root` for existing installations.
- Only users who update their Compose files will get the new behavior.
- New installations based on the Compose files in the repository will use the non-root user by default.
- The README has upgrade instructions for existing installations.

Allow to run the app as a non-root user (opt-in)

---

Dockerfile
requirements.txt
tronbyt_server/__init__.py
tronbyt_server/api.py
tronbyt_server/manager.py

See https://github.com/tronbyt/server/issues/137
No client firmware using this endpoint exists yet.
Here's a local test showing that images are pushed over the connection:

Add a WebSocket route to push images to devices

---

tronbyt_server/api.py
tronbyt_server/db.py

initial working.

---

run
tronbyt_server/templates/auth/login.html
tronbyt_server/templates/auth/register.html
tronbyt_server/templates/manager/addapp.html
tronbyt_server/templates/manager/uploadapp.html

See https://github.com/tronbyt/server/issues/206

Apply w3-button style to submit buttons

---

docker-compose.https.yaml
tronbyt_server/templates/manager/index.html

Make the border of device container solid black line so that you can easily see when one device ends and another starts especially when the apps are showing.

slight change to index

---

.devcontainer/postCreateCommand.sh
.github/workflows/build.yml
tronbyt_server/__init__.py
tronbyt_server/manager.py

Requires https://github.com/tronbyt/pixlet/pull/57 to be submitted and deployed first.
See https://github.com/tronbyt/server/issues/138

Use the app output returned by libpixlet

---

tronbyt_server/__init__.py
tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/models/app.py
tronbyt_server/templates/manager/configapp.html
tronbyt_server/templates/manager/updateapp.html

No live updates on configapp though, will require doing multipart-mime reseponse in preview function

Save pixlet message to db and display on updateapp and configapp pages.

---

tronbyt_server/__init__.py
tronbyt_server/api.py
tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/models/app.py
tronbyt_server/templates/manager/configapp.html
tronbyt_server/translations/de/LC_MESSAGES/messages.po

- Add German translations
- Change formatting from JSON to lines
- Pass app object instead of parsing the webp filename

Debug output

---

tronbyt_server/api.py
tronbyt_server/manager.py

Remove manual locking in the Websocket loop

Only store pushed apps with installation_ids

---

tronbyt_server/manager.py

https://github.com/tronbyt/server/security/code-scanning/70

Sanitize user-provided repository URLs

---

tronbyt_server/db.py
tronbyt_server/firmware/correct_firmware_esptool.py
tronbyt_server/models/device.py
tronbyt_server/templates/manager/create.html
tronbyt_server/templates/manager/index.html
tronbyt_server/templates/manager/update.html

add tronbyt_s3_wide as flashable device

---

tronbyt_server/db.py

Make the end hour exclusive, so that night mode ends at end_hour:00 instead of end_hour:59.

Fix night mode

---

tronbyt_server/manager.py

return 404 if non-existant device_id

---

tronbyt_server/auth.py
tronbyt_server/db.py
tronbyt_server/models/user.py
tronbyt_server/static/css/style.css
tronbyt_server/static/js/theme.js
tronbyt_server/templates/auth/login.html
tronbyt_server/templates/base.html
tronbyt_server/translations/de/LC_MESSAGES/messages.po

Make appearance (light / dark mode) configurable

---

tronbyt_server/manager.py
tronbyt_server/models/app.py

use recommended interval from manifest when adding app.

---

render.yaml

set server_port and protocol
remove autodeply and region
fromservice ?
try envvarkey
no ${
caps
value not VALUE
remove sync
add port too
also server_hostanme
key not Key
indent

add render.yaml for render deployments

---

tronbyt_server/templates/manager/update.html

so it's easy to test push to a device.

add the curl push command example to edit page

---

tronbyt_server/manager.py

There was a race condition where an edit operation could write during a render and then the render process would save old data reverting the edit.

call save_app instead of save_user after calls to render

---

.gitignore
tronbyt_server/db.py
tronbyt_server/manager.py
tronbyt_server/models/app.py
tronbyt_server/system_apps.py
tronbyt_server/templates/manager/addapp.html
tronbyt_server/templates/manager/configapp.html
tronbyt_server/templates/manager/updateapp.html

* Add a date default (today, plus one week) to the custom schedules 
* Add New Sorting Options to the Apps Page
* Newest - Uses File Mod times - refreshes with admin system refresh -- New DEFAULT SORT
* System - Installed First - Alpha A-Z - Original Sort
* Alpha - A -Z by Name
* Rev Alpha - Z - A by Name
* Hide Installed - Don't display installed apps
* New Styling for Installed Apps
Fix a Bug in "App App" >> Cancel workflow (Doesn't add app as disabled)

New Sorting Options

---

README.md
tronbyt_server/__init__.py
tronbyt_server/firmware_utils.py
tronbyt_server/manager.py

Fix #344 by downloading firmware files in a subprocess

Fix crash on macOS
